-- This is not the language server, this is a plugin to enhance the
-- LSP installed and managed by mason
-- return {
	-- "mfussenegger/nvim-jdtls",
	-- config = function()
		-- local cmd = { "/path/to/jdt-language-server/bin/jdtls" }
		-- local jdtls_dir = vim.fn.stdpath("data") .. "mason/packages/jdtls/"
		-- local config_dir = jdtls_dir .. "config_linux"
		-- local plugins_dir = jdtls_dir .. "plugins/"
		-- local jar_file = plugins_dir .. "org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.900.v20240129-1338.jar"
		-- local root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1])
	-- end,
-- }
--
-- This should be in a filetype hook inside ftplugin directory
